plugins {
    id "com.android.application"
}

android {
    namespace "ru.bvb.ratingboard"
    compileSdk 33

    defaultConfig {
        applicationId "ru.bvb.ratingboard"
        minSdk 23
        targetSdk 33
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
